---
# proxy_prefix:
#   get.helm.sh: https://get.helm.sh
#   github.com: https://raw.githubusercontent.com
#   raw.githubusercontent.com: https://raw.githubusercontent.com

# Helm version number
helm_version: '3.14.4'

# The CPU architecture of the Helm executable to install
helm_architecture: 'amd64'

# Mirror to download Helm from
helm_mirror: 'https://get.helm.sh'

# Dir where Helm should be installed
helm_install_dir: '/usr/local/share/helm'

# Directory to store files downloaded for Helm
helm_download_dir: "{{ x_ansible_download_dir | default(ansible_env.HOME + '/.ansible/tmp/downloads') }}"

# The OS of the Helm redistributable
helm_os: 'linux'

# File name of the Helm redistributable file
helm_redis_filename: 'helm-v{{ helm_version }}-{{ helm_os }}-{{ helm_architecture }}.tar.gz'
