prometheus:

  ## nodePort
  service:
    type: NodePort

  prometheusSpec:
    serviceMonitorSelector:
      matchLabels:
        release: prometheus

    ruleSelector:
      matchLabels:
        release: prometheus

    podMonitorSelector:
      matchLabels:
        release: prometheus

    scrapeConfigSelector:
      matchLabels:
        release: prometheus

    probeSelector:
      matchLabels:
        release: prometheus

    ruleSelectorNilUsesHelmValues: false
    serviceMonitorSelectorNilUsesHelmValues: false
    podMonitorSelectorNilUsesHelmValues: false
    probeSelectorNilUsesHelmValues: false
    scrapeConfigSelectorNilUsesHelmValues: false

alertmanager:

  ## Deploy alertmanager
  enabled: true

  ## Default ayarları siliyoruz
  config:
    global:
      resolve_timeout: 5m

  ## nodePort
  service:
    type: NodePort

  alertmanagerSpec:
    replicas: 2
    alertmanagerConfigSelector:
      matchLabels:
        resource: prometheus
    alertmanagerConfiguration:
      name: gmail-alertmanager

grafana:

  ## Deploy grafana
  enabled: true

  defaultDashboardsTimezone: browser
  adminPassword: grafana

  ## nodePort
  service:
    type: NodePort
    nodePort: 30904