---
- name: Add kube-prometheus-stack helm chart
  kubernetes.core.helm_repository:
    name: prometheus-community
    repo_url: "{{ kube_prometheus_stack_helm_chart }}"

- name: Update Helm repos
  ansible.builtin.command: helm repo update

- name: Install kube-prometheus-stack helm chart
  kubernetes.core.helm:
    name: "{{ kube_prometheus_stack_release_name }}"
    chart_ref: "prometheus-community/{{ kube_prometheus_stack_release_name }}"
    release_namespace: "{{ kube_prometheus_stack_release_namespace }}"
    chart_version: "{{ kube_prometheus_stack_chart_version }}"
    create_namespace: true
    update_repo_cache: true
    wait: false
    values: "{{ lookup('template', 'values.yml') | from_yaml }}"
