---

- name: Cluster prep
  hosts: k3s_cluster
  gather_facts: true
  become: true
  roles:
    - role: prereq
    - role: airgap
    #- role: raspberrypi

- name: Setup K3S server
  hosts: server
  become: true
  roles:
    - role: k3s_server
    - role: install_helm
    - role: k3s_server_config
    - role: install_prometheus
      become_user: "vagrant"
      install_prometheus_install: true
      when:
        - inventory_hostname == groups['server'][0]
        - install_prometheus_install

- name: Setup K3S agent
  hosts: agent
  become: true
  roles:
    - role: k3s_agent
